[package]
name = "cosmic-launcher"
version = "0.1.0"
authors = ["Ashley Wulber <ashley@system76.com>"]
edition = "2021"

[dependencies]
freedesktop-icons = "0.2.2"
libcosmic = { git = "https://github.com/pop-os/libcosmic/", branch = "master", default-features = false, features = ["wayland", "tokio"] }
serde = { version = "1.0.134", features = ["derive"] }
pop-launcher-service = { git = "https://github.com/wash2/launcher.git", branch = "cosmic-toplevel" }
pop-launcher = { git = "https://github.com/wash2/launcher.git", branch = "cosmic-toplevel" }
serde_json = "1.0.75"
tokio-stream = "0.1.8"
tokio = { version = "1.17.0", features = ["sync", "rt", "rt-multi-thread", "process"] }
log = "0.4"
pretty_env_logger = "0.4"
once_cell = "1.9"
futures = "0.3.21"
xdg = "2.4.0"
anyhow = "1.0"
# Application i18n
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.3.0"
zbus = "3.5.0"
glob = "0.3.0"
freedesktop-desktop-entry = "0.5.0"
shlex = "1.1.0"
